name: Build Cross-Platform Mouse Auto Mover

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build Windows Application
      run: |
        cd windows
        dotnet build --configuration Release
        dotnet publish --configuration Release --runtime win-x64 --self-contained true --output ../releases/windows
    
    - name: Verify Windows Build
      run: |
        if (Test-Path "releases/windows/MouseAutoMover.exe") {
          Write-Host "✅ Windows build successful"
          Get-Item "releases/windows/MouseAutoMover.exe" | Format-Table Name, Length
        } else {
          Write-Host "❌ Windows build failed"
          exit 1
        }
      shell: powershell
    
    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MouseAutoMover-Windows
        path: releases/windows/

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build macOS Application
      run: |
        cd macos
        dotnet build --configuration Release
        dotnet publish --configuration Release --runtime osx-x64 --self-contained true --output ../releases/macos
    
    - name: Verify macOS Build
      run: |
        if [ -f "releases/macos/MouseAutoMover.MacOS" ]; then
          echo "✅ macOS build successful"
          ls -la releases/macos/MouseAutoMover.MacOS
        else
          echo "❌ macOS build failed"
          exit 1
        fi
    
    - name: Upload macOS Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MouseAutoMover-macOS
        path: releases/macos/

  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Windows Artifacts
      uses: actions/download-artifact@v4
      with:
        name: MouseAutoMover-Windows
        path: releases/windows/
    
    - name: Download macOS Artifacts
      uses: actions/download-artifact@v4
      with:
        name: MouseAutoMover-macOS
        path: releases/macos/
    
    - name: Create Release Archives
      run: |
        cd releases
        zip -r MouseAutoMover-Windows.zip windows/
        tar -czf MouseAutoMover-macOS.tar.gz macos/
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          releases/MouseAutoMover-Windows.zip
          releases/MouseAutoMover-macOS.tar.gz
          README.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
